### PR TITLE
Document CIRRUS_CLONE_SUBMODULES

### PR DESCRIPTION
**Pull request by edigaryev**
See https://github.com/cirruslabs/cirrus-ci-agent/pull/114.

### CODE REVIEW

**Comment by emaste** [comment]
I tried to use this on my submodules project: https://github.com/emaste/freebsd/commit/8c152bf68785cf9f5f33e478d2817d4c3bf5bd4e

But it looks like the submodules were not populated: https://cirrus-ci.com/task/6005207805984768

I'll try to look into what happened. Maybe interaction with `CIRRUS_CLONE_DEPTH`?

**Comment by edigaryev** [comment]
> I tried to use this on my submodules project: [emaste/freebsd@8c152bf](https://github.com/emaste/freebsd/commit/8c152bf68785cf9f5f33e478d2817d4c3bf5bd4e)
> 
> But it looks like the submodules were not populated: https://cirrus-ci.com/task/6005207805984768
> 
> I'll try to look into what happened. Maybe interaction with `CIRRUS_CLONE_DEPTH`?

You did everything right! This just hasn't been rolled out yet.

It probably will be after this PR gets merged 🙌

**Comment by fkorotkov** [comment]
It should be available now.

**Comment by emaste** [comment]
Looks like it is not working for me - compare https://cirrus-ci.com/build/5139496078409728 and https://cirrus-ci.com/task/4625231508668416

The first sets `CIRRUS_CLONE_SUBMODULES: true` and the second runs `git submodule init` and `git submodule update`. The first reports
```
Updating submodules...
Failed to update submodules: object not found!
```

**Comment by edigaryev** [comment]
> Looks like it is not working for me - compare https://cirrus-ci.com/build/5139496078409728 and https://cirrus-ci.com/task/4625231508668416
> 
> The first sets `CIRRUS_CLONE_SUBMODULES: true` and the second runs `git submodule init` and `git submodule update`. The first reports
> 
> ```
> Updating submodules...
> Failed to update submodules: object not found!
> ```

It seems that the https://github.com/emaste/drm-kmod/commit/b57b441102e9989f5a7d4c9f3c7f29c3790c53f0 commit referenced from the [`drm-kmod` submodule](https://github.com/edigaryev/freebsd/blob/2a368c39cfeff112e3599040bd2c1a6fb7c684f4/.gitmodules#L8-L10) is orphaned and that causes the `object not found` error.

What's interesting though is how `git submodule update` manages to fetch it anyway, while [go-git](https://github.com/go-git/go-git) fails.

I'll take a look at this, but for a quick workaround you can assign this commit to some branch or tag [as recommended in GitHub documentation](https://docs.github.com/en/github/committing-changes-to-your-project/commit-exists-on-github-but-not-in-my-local-clone#the-branch-that-contained-the-commit-was-deleted).

**Comment by edigaryev** [comment]
Turns out that the official Git implementation does a second fetch attempt, while [go-git](https://github.com/go-git/go-git) doesn't, more details in https://github.com/go-git/go-git/pull/284.

Let's see how long it takes for the upstream to merge the fix, while you can still use the workaround above.

**Pull request merged**
