### PR TITLE
Document GKE Pipe

### LINKED ISSUE #387: docker pipe on GKE
After a bit of try and error I found that apparently docker pipe cannot be executed on your own GKE cluster. So where / how is docker pipe actually executed?
The docs are not very clear on the whole execution environment / limitations of docker pipe imho: https://cirrus-ci.org/guide/docker-pipe/

Would it be possible to add support for docker pipe on GKE?

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes #387

FYI @geekflyer

### CODE REVIEW

**Comment by geekflyer** [comment]
awesome, thanks!

**Comment by geekflyer** [comment]
awesome, thanks!

**Comment by geekflyer** [comment]
oh btw, does this work with eks as well? not that i personally care, but maybe others do :-D

**Comment by fkorotkov** [comment]
No `eks_pipe` yet. 😅

**Pull request merged**
