### PR TITLE
Effect is the noun

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by fkorotkov** [comment]
Thank you!

**Comment by RDIL** [comment]
psst @fkorotkov I have 3 other PRs open could you take a look at those also

**Comment by fkorotkov** [comment]
I never know when that are ready for a review since you open them first and then add new commits. Will take a look now. 🙌

**Comment by RDIL** [comment]
I do that because I need a branch to work off of 😅 , I'll try not to in the future!

**Comment by fkorotkov** [comment]
You can have a branch on your fork without an open PR. ;-)

**Comment by RDIL** [comment]
Right but sometimes I accidentally use `fork@master` meaning that I don't have an active copy of `upstream@master` in my fork :(

**Pull request merged**
