### PR TITLE
Example of how Ruby can be installed on Windows

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by fkorotkov** [comment]
I'll work on https://github.com/cirruslabs/docker-images-windows/issues/4 to make the snippet smaller. 🙌

**Comment by fkorotkov** [comment]
@dotdoom BTW why do you need `msys2` for Ruby on Windows?

**Comment by RDIL** [comment]
I can explain that - it is because some gems have `native` extensions (written in C based languages), and the `native` extensions can't be directly downloaded from RubyGems or a different provider, it instead downloads the sources and builds them locally.  It is a side effect of Windows not being an officially supported platform.

**Comment by dotdoom** [comment]
Thanks @RDIL, that's exactly why I need `msys2`.
@fkorotkov, you may use this command as a litmus test: `gem install fastlane`

**Comment by duckinator** [comment]
Here's a real-world example, for cases where you don't need native extensions: https://github.com/duckinator/inq/blob/master/.cirrus.yml#L69-L84

Avoiding native extensions, and thus msys2 and related things, cut Windows CI run time for inq from 9 minutes to 2.5 minutes.

**Comment by duckinator** [comment]
Also, using `refreshenv` any time new executables are added + as the first `script` step makes it a lot less cumbersome in terms of managing the locations of files. (You can just use the defaults, that way.)

**Comment by RDIL** [comment]
Some projects do require N.E.s though.

**Comment by duckinator** [comment]
@RDIL yeah, I know. I was just mentioning this for cases when you _don't_ need them, because if msys2 isn't needed, dropping it will immediately cut ~8 minutes off of CI.

**Comment by duckinator** [comment]
Although I think cirruslabs/docker-images-windows#8 may make my comments entirely irrelevant, since it wouldn't be installing msys2 during CI. :slightly_smiling_face:

**Comment by dotdoom** [comment]
@duckinator be careful with `refreshenv` though – in my experience it tends to overwrite environment variables (esp. `PATH`) set via `env:`, which breaks programs installed via different means than Chocolatey.

**Comment by dotdoom** [comment]
( #248 )

**Comment by duckinator** [comment]
@dotdoom oh, I hadn't noticed issues with that -- super good to know!

**Comment by fkorotkov** [comment]
I think now Ruby can be installed like in @duckinator's example but with `cirrusci/windowsservercore:cmake` image:

```yaml
Windows_task:
  env:
    matrix:
      - RUBY_VERSION: 2.5.3.101
      - RUBY_VERSION: 2.6.3.1
  windows_container:
    os_version: 2019
    image: cirrusci/windowsservercore:cmake
  install_script:
    - choco install -y ruby --version %RUBY_VERSION%
    - refreshenv
    - gem install bundler
    - bundle install
  script:
    - refreshenv
    - bundle exec rake spec
```

Could you please try that?

**Comment by RDIL** [comment]
pretty sure that 2.5 version is broken because it won't start for me 🤔 
2.6 looks fine for now

**Comment by dotdoom** [comment]
I thought it already worked before with bundler, and it still doesn't seem to work with native extensions - https://github.com/cirruslabs/cirrus-ci-docs/pull/245#issuecomment-485441927. Or did I misunderstand the intent here?

```
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.
    current directory: C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/unf_ext-0.0.7.6/ext/unf_ext
```

[CI](https://cirrus-ci.com/build/6101828790386688) | [Source](https://github.com/dotdoom/onfailure)

**Pull request closed without merging**
