### PR TITLE
Clarify support of available code hosting platforms

### LINKED ISSUE #503: Clarify docs/marketing site: Github only?
This is a "feature request" for the documentation to clarify who the target market (today) is:

From reading around here and in the documentation, I get the impression that Cirrus today works only with Git repositories stored in Github.

Is that true? If so it would be great if it was obvious on the home page of the site: It's a CI tool for your projects on Github. (I think?)

(It seems a little odd, I'm used to a slightly older generation of tools were you could point them to an arbitrary source code repository. )

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes #503

PTAL @kylecordes

### CODE REVIEW

**Comment by fkorotkov** [comment]
@RDIL indeed! Something got screwed. 🤔

**Comment by kylecordes** [comment]
Somewhat cheekily, I went ahead and filled in the form :-)

**Comment by RDIL** [comment]
Same haha

**Comment by fkorotkov** [comment]
Thank you both!

**Pull request merged**
